### ISSUE TITLE
Improve filtering support

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#14]
Filters are a type of expressions used for removing elements when certain conditions are not met.
Right now, we can filter out features from rendering, but there is no special semantics for it.
In this issue we define the list of available expressions and usage examples.

In order to make the filters easy to use we add a new property `filter` to the `styleSpec` object this property will affect the alpha value making elements invisible when the filter predicate is evaluated to false (or 0).

Filtering will be done in the client whenever possible, however there are always cases in which you can not filter in client for example tremendous datasets. For those cases we define a breakpoint when we decide to filter in the server. This is done by the library automatically and the user has no control over it.

## Public Api

I like the [mongodb operators naming](https://docs.mongodb.com/manual/reference/operator/query/#query-selectors) (@iago)

### Comparison
 - `s.eq`: Matches values that are equal to a specified value.
 - `s.ne`: Matches values that are not equal to a specified value.
 - `s.gt`: Matches values that are greater than a specified value.
 - `s.gte`: Matches values that are greater than or equal to a specified value.
 - `s.lt`: Matches values that are less than a specified value.
 - `s.lte`: Matches values that are less or equal to a specified value.
 - `s.in`: Matches any value in the given list. *
 - `s.nin`: Matches any value in not the given list. *
 - `s.between`: Matches numerical values betweeen the given numbers (limits included) *

*This filters are the only allowed in server side filtering mode.

### Logical
 - `s.TRUE`:  Evaluates to true
 - `s.FALSE`:  Evaluates to false
 - `s.and`:  Perform a logical `and` between the parameters.
 - `s.or`:  Perform a logical `or` between the parameters.
 - `s.not`: Inverts the Boolean predicate

## Use cases
Filter populated places dataset, show only very populated places.
``` javascript
const $population = s.property('pop_max');
const style = new carto.Style({
  filter: s.gt($population, 1000000)
});
```

## TODO

- [x] Define public API.
- [x] Define and implement a naive use-case.
- [x] Review which expressions can be filtered in the server.
- [x] Implement all filters in the list with use cases/examples
- [x] Fix cache bug: One cache per shader

- [x] Define client/server breakpoint (when we should try to render in the server).
- [x] Implement a method to delegate filtering to the server

**Comment by davidmanzanares** [comment]
After talking with @rochoa, we decided to lower a little bit the expectations of the new functionality that we want to propose for Maps API. In particular, we rejected the idea of general support for expressions on the server.

Basically, he proposed to allow for the two most common type of filters (which could only be combined with their AND):

- Whitelisting and blacklisting for categories. Basically, accepting all categories present in a whitelist or rejecting all categories present in a blacklist.
- "Between" for numerical properties. Accepting all properties which are within a [min, max] range.

Of course, not all filters can be expressed in this way, and not all datasets should be server-side filtered. For both cases, client-side filtering should be used.

Therefore I have the following list of things that I think that should be done:
- [ ] `filter:` style property
- [ ] Compare functionality. Including exposing: `<`, `>`, `==`,... in the style string API and `filter: between($price, 10, 50)`
- [ ] Boolean functionality. Including: and, or, not, true, false
- [ ] Category filtering: `filter: in($type, 'red', 'blue', 'green')`
- [ ] Automatic delegation on the server when the dataset is large **and** the filter is one of: `in(wadus)`, `not(in(wadus))`, `between(wadus)`, `property COMPARE constant`

**Comment by IagoLast** [comment]
## Public Api

I like the [mongodb operators naming](https://docs.mongodb.com/manual/reference/operator/query/#query-selectors)

### Comparison
 - `s.eq`: Matches values that are equal to a specified value.
 - `s.ne`: Matches values that are not equal to a specified value.
 - `s.gt`: Matches values that are greater than a specified value.
 - `s.gte`: Matches values that are greater than or equal to a specified value.
 - `s.lt`: Matches values that are less than a specified value.
 - `s.lte`: Matches values that are less or equal to a specified value.
 - `s.in`: Matches any value in the given list.
 - `s.nin`: Matches any value in not the given list.
 - `s.bet`: Matches numerical values betweeen the given numbers (limits included)

### Logical
 - `s.true`: 
 - `s.false`: 
 - `s.and`: 
 - `s.or`: 
 - `s.not`:

**Comment by davidmanzanares** [comment]
I forgot about one "small" detail. We are not taking filtering into account for metadata yet. Both in viewport and in global aggregations.
